"use strict";

const PROJECTS_KEY = "inspectoraProjectsV1";
const DRAFT_KEY = "inspectoraProjectDraftV1";
const statusSteps = [
  { label: "Projekt angelegt", note: "Leistung und Objektdaten wurden erfasst." },
  { label: "Unterlagen prüfen", note: "Vorhandenes Material wird gesichtet und zugeordnet." },
  { label: "In Bearbeitung", note: "Das vereinbarte Ergebnis wird vorbereitet." },
  { label: "Ergebnis prüfen", note: "Das Ergebnis befindet sich in der abschließenden Kontrolle." },
  { label: "Abgeschlossen", note: "Das Projekt ist fertiggestellt." }
];

const serviceData = {
  owner:{service:"Eigentümerbericht",description:"Objektzustand, laufende Maßnahmen und offene Entscheidungen in einer verständlichen Übersicht.",audience:"Verwaltung, Eigentümer, Asset Management",output:"Eigentümerbericht mit Statusübersicht",input:"Fotos, Notizen, Angebote, Objektangaben",benefits:["Angaben aus mehreren Quellen zusammenführen","offene Punkte sichtbar machen","Entscheidungsbedarf klar kennzeichnen"]},
  object:{service:"Objektbericht",description:"Fotos, Notizen und Objektangaben werden nach Bereichen geordnet und als nachvollziehbarer Bericht aufbereitet.",audience:"Verwaltung, Bestand, Projektleitung",output:"strukturierter Objektbericht",input:"Besichtigungsfotos, Notizen, Stammdaten",benefits:["Objektbereiche einheitlich dokumentieren","Feststellungen nachvollziehbar zuordnen","Bericht direkt weiterverwenden"]},
  defects:{service:"Mängel & Maßnahmen",description:"Feststellungen werden nach Bereich, Dringlichkeit, Zuständigkeit und nächstem Schritt geordnet.",audience:"Verwaltung, Technik, Eigentümer",output:"priorisierte Maßnahmenübersicht",input:"Mängelfotos, Notizen, Handwerkerstände",benefits:["Prioritäten klar trennen","Zuständigkeiten erfassen","offene Entscheidungen markieren"]},
  photos:{service:"Fotodokumentation",description:"Unsortierte Bilder werden ausgewählt, nach Räumen gegliedert und sachlich beschriftet.",audience:"Verwaltung, Eigentümer, Dienstleister",output:"sortierte Fotodokumentation",input:"Objektfotos und kurze Hinweise",benefits:["Dubletten aussortieren","Bilder Bereichen zuordnen","Schäden und Details gesondert zeigen"]},
  expose:{service:"Exposé-Paket",description:"Objektdaten, Unterlagen und Bildmaterial werden geprüft und zu einem vollständigen Vermarktungspaket zusammengeführt.",audience:"Makler, Vermarktung, Eigentümer",output:"Datenblatt, Bildauswahl, Text und Klärungsliste",input:"Grundriss, Energieausweis, Fotos, Notizen",benefits:["Angaben zwischen Quellen abgleichen","fehlende Daten separat ausweisen","Bildauswahl und Unterlagen vereinheitlichen"]},
  documents:{service:"Unterlagen strukturieren",description:"Verteilte Dateien und Angaben werden als geordnete Objektakte mit Register und Prüfliste zusammengeführt.",audience:"Verwaltung, Asset Management, Bestand",output:"Objektakte mit Dokumentenregister",input:"PDF, Tabellen, E-Mails, Dokumentenfotos",benefits:["Dateien einheitlich benennen","widersprüchliche Angaben markieren","fehlende Dokumente auflisten"]}
};

const caseData = {
  expose:{inputTitle:"Fotos, Grundriss und Objektdaten",inputs:[["JPG","28 Objektfotos","teilweise doppelt, ohne Raumzuordnung"],["PDF","Grundriss","Raumbezeichnungen vorhanden"],["PDF","Energieausweis","gültig bis 2031"],["TXT","11 Besichtigungsnotizen","Ausstattung, Lage und Zustand"]],checks:[["ok","Wohnfläche und Zimmerzahl vorhanden"],["warn","Baujahr nicht eindeutig belegt"],["warn","Angabe zu Hausgeld oder Nebenkosten fehlt"]],outputTitle:"Vermarktungsfertiges Exposé-Paket",type:"Vermarktungspaket",code:"EX-2026-021",title:"Wohnungsdaten geprüft und einheitlich zusammengeführt",text:"Die Angaben aus Grundriss, Energieausweis, Notizen und Bildmaterial wurden abgeglichen. Widersprüchliche oder fehlende Punkte sind getrennt markiert. Für die Vermarktung stehen ein Datenblatt, eine sortierte Bildauswahl, ein sachlicher Exposé-Text und eine Liste der noch zu klärenden Angaben bereit.",results:[["01","Objektdatenblatt","einheitliche Angaben für Portal und Exposé"],["02","16 ausgewählte Fotos","sortiert, beschriftet und ohne Dubletten"],["03","Exposé-Text","aus den geprüften Daten erstellt"],["04","Klärungsliste","3 fehlende oder unklare Angaben"]],service:"Exposé-Paket",details:"Fotos, Grundriss, Energieausweis und Objektdaten prüfen und als vollständiges Vermarktungspaket aufbereiten."},
  owner:{inputTitle:"Fotos, Handwerkerstände und Rückfragen",inputs:[["JPG","19 Zustandsfotos","Wohnung, Keller und Gemeinschaftsflächen"],["PDF","2 Handwerkerangebote","Malerarbeiten und Bodenreparatur"],["MAIL","4 Rückmeldungen","Verwaltung, Mieter und Dienstleister"],["TXT","Übergabenotizen","Zählerstände und offene Punkte"]],checks:[["ok","Maßnahmen nach Objektbereich zugeordnet"],["ok","Angebote den offenen Punkten zugeordnet"],["warn","Freigabe für Bodenreparatur noch offen"]],outputTitle:"Entscheidungsfähiger Eigentümerbericht",type:"Eigentümerinformation",code:"EB-2026-021",title:"Zustand, Kostenstände und Entscheidungen in einer Übersicht",text:"Der Bericht trennt erledigte Arbeiten, offene Maßnahmen und notwendige Entscheidungen. Zu jeder Position sind Bildnachweis, aktueller Status und vorhandene Kostenangaben hinterlegt.",results:[["01","Kurzstatus","aktueller Stand des Objekts"],["02","Maßnahmenübersicht","erledigt, offen oder in Prüfung"],["03","Kostenstände","Angebote den Positionen zugeordnet"],["04","Entscheidungsbedarf","Freigaben klar markiert"]],service:"Eigentümerbericht",details:"Aus Fotos, Handwerkerständen, Angeboten und Übergabenotizen einen entscheidungsfähigen Eigentümerbericht erstellen."},
  object:{inputTitle:"Besichtigungsfotos und Objektangaben",inputs:[["JPG","34 Fotos","Wohnung und Gemeinschaftsflächen"],["TXT","Besichtigungsnotizen","Zustand und Ausstattung"],["PDF","Grundriss","Flächen und Raumaufteilung"],["DATA","Objektstammdaten","Baujahr und Gebäudetechnik"]],checks:[["ok","Fotos nach Bereichen zugeordnet"],["ok","Grundriss mit Notizen abgeglichen"],["warn","Angabe zur Heizungsart prüfen"]],outputTitle:"Strukturierter Objektbericht",type:"Objektdokumentation",code:"OB-2026-021",title:"Objektzustand nach Bereichen nachvollziehbar dokumentiert",text:"Wohnung, Keller und Gemeinschaftsflächen wurden getrennt erfasst. Sichtbare Feststellungen sind den jeweiligen Bereichen und Fotos zugeordnet. Unklare Angaben erscheinen als eigener Prüfpunkt.",results:[["01","Objektübersicht","Stammdaten und Kurzstatus"],["02","Bereichsberichte","Wohnung, Keller, Gemeinschaft"],["03","Bildnachweise","Feststellungen eindeutig zugeordnet"],["04","Prüfpunkte","unklare Angaben separat"]],service:"Objektbericht",details:"Besichtigungsfotos, Grundriss, Notizen und Stammdaten als strukturierten Objektbericht zusammenführen."},
  defects:{inputTitle:"Mängelfotos, Notizen und Termine",inputs:[["JPG","17 Mängelfotos","Keller, Eingang und Müllraum"],["TXT","9 Feststellungen","ohne einheitliche Priorität"],["MAIL","2 Handwerkerrückmeldungen","Termine teilweise offen"],["PDF","Angebot Elektriker","Kellerbeleuchtung"]],checks:[["ok","Feststellungen nach Bereichen sortiert"],["warn","Feuchtigkeitsursache noch nicht geklärt"],["warn","Termin für Türschließer fehlt"]],outputTitle:"Priorisierte Mängel- und Maßnahmenliste",type:"Maßnahmensteuerung",code:"MM-2026-021",title:"Offene Punkte nach Dringlichkeit und Zuständigkeit geordnet",text:"Jede Feststellung enthält Bereich, Bildnachweis, Priorität, Zuständigkeit und nächsten Schritt. Ungeklärte Ursachen werden nicht als fertige Diagnose dargestellt, sondern als Prüfauftrag markiert.",results:[["01","Dringlichkeit","kurzfristig, regulär oder beobachten"],["02","Zuständigkeit","Verwaltung, Handwerker oder Prüfung"],["03","Bildnachweise","je Position eindeutig zugeordnet"],["04","nächste Schritte","Termin, Angebot oder Freigabe"]],service:"Mängel & Maßnahmen",details:"Mängelfotos, Notizen, Angebote und Handwerkerstände als priorisierte Maßnahmenliste ordnen."},
  photos:{inputTitle:"Unsortierte Aufnahmen aus Besichtigung und Übergabe",inputs:[["JPG","53 Originalfotos","mehrere Dubletten und Detailaufnahmen"],["TXT","Raumliste","Wohnzimmer, Schlafen, Bad, Küche"],["JPG","Zählerstände","Strom, Wasser und Heizung"],["NOTE","3 Schadenhinweise","ohne Bildzuordnung"]],checks:[["ok","Bilder nach Räumen sortiert"],["ok","Dubletten und unscharfe Fotos entfernt"],["warn","ein Schadenhinweis ohne eindeutiges Foto"]],outputTitle:"Geordnete Fotodokumentation",type:"Bilddokumentation",code:"FD-2026-021",title:"Relevante Aufnahmen in nachvollziehbarer Reihenfolge",text:"Die Originalbilder werden gesichtet, nach Räumen sortiert und mit kurzen sachlichen Beschriftungen versehen. Dubletten und unbrauchbare Aufnahmen werden nicht übernommen.",results:[["01","26 verwendete Fotos","aus 53 Originalaufnahmen ausgewählt"],["02","Raumstruktur","klare Reihenfolge nach Bereichen"],["03","Beschriftungen","Ort und sichtbarer Inhalt"],["04","Sonderabschnitte","Details, Schäden und Zählerstände"]],service:"Fotodokumentation",details:"Unsortierte Besichtigungs- und Übergabefotos auswählen, nach Räumen ordnen und sachlich beschriften."},
  documents:{inputTitle:"Verteilte Objektunterlagen aus mehreren Quellen",inputs:[["PDF","Grundriss und Energieausweis","unterschiedliche Dateinamen"],["XLS","Miet- und Flächendaten","mehrere Tabellenblätter"],["MAIL","Verwalterauskünfte","Hausgeld und Rücklage"],["JPG","Dokumentenfotos","nicht eindeutig zugeordnet"]],checks:[["ok","Dateien nach Dokumentart erkannt"],["warn","Wohnflächenangabe weicht zwischen Quellen ab"],["warn","aktueller Wirtschaftsplan fehlt"]],outputTitle:"Geordnete Objektakte mit Prüfliste",type:"Unterlagenübersicht",code:"OU-2026-021",title:"Vorhandene, fehlende und widersprüchliche Unterlagen getrennt",text:"Die Unterlagen werden einheitlich benannt, nach Themen abgelegt und in einer zentralen Übersicht erfasst. Abweichende Angaben werden als Klärungspunkt ausgewiesen.",results:[["01","Dokumentenregister","Dateiname, Stand und Dokumentart"],["02","einheitliche Ablage","Stammdaten, Technik, Vertrag und Kosten"],["03","Abweichungsliste","widersprüchliche Angaben sichtbar"],["04","Nachforderungsliste","fehlende Dokumente klar benannt"]],service:"Unterlagen strukturieren",details:"Verteilte Objektunterlagen aus PDF, Tabellen, E-Mail und Fotos als geordnete Objektakte mit Prüfliste aufbereiten."}
};

const $ = selector => document.querySelector(selector);
const $$ = selector => Array.from(document.querySelectorAll(selector));
let currentServiceKey = "owner";
let currentCaseKey = "expose";
let currentWizardStep = 1;
let selectedProjectId = null;
let editingProjectId = null;
let selectedFileNames = [];
let mapInstance = null;

function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2200)}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
function getProjects(){try{return JSON.parse(localStorage.getItem(PROJECTS_KEY))||[]}catch{return []}}
function saveProjects(projects){localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects))}
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}

function setupNavigation(){const toggle=$("#navToggle"),links=$("#navLinks");toggle?.addEventListener("click",()=>{const open=links.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});$$("#navLinks a").forEach(link=>link.addEventListener("click",()=>links.classList.remove("open")));window.addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;$("#scrollProgress").style.width=`${max>0?(scrollY/max)*100:0}%`})}

function renderService(key){const data=serviceData[key];if(!data)return;currentServiceKey=key;$("#serviceTitle").textContent=data.service;$("#serviceDescription").textContent=data.description;$("#serviceAudience").textContent=data.audience;$("#serviceOutput").textContent=data.output;$("#serviceInput").textContent=data.input;$("#serviceBenefits").innerHTML=data.benefits.map(item=>`<span>✓ ${escapeHtml(item)}</span>`).join("");$$(".service-option").forEach(btn=>btn.classList.toggle("active",btn.dataset.serviceKey===key))}
function setupServices(){$$(".service-option").forEach(btn=>btn.addEventListener("click",()=>renderService(btn.dataset.serviceKey)));$("#serviceStartButton").addEventListener("click",()=>startProjectWithService(serviceData[currentServiceKey].service,""));renderService("owner")}

function renderCase(key){const data=caseData[key];if(!data)return;currentCaseKey=key;$("#caseInputTitle").textContent=data.inputTitle;$("#caseInputList").innerHTML=data.inputs.map(item=>`<div><span>${escapeHtml(item[0])}</span><p><strong>${escapeHtml(item[1])}</strong><small>${escapeHtml(item[2])}</small></p></div>`).join("");$("#caseCheckList").innerHTML=data.checks.map(item=>`<li class="${item[0]}"><b>${item[0]==="ok"?"✓":"!"}</b>${escapeHtml(item[1])}</li>`).join("");$("#caseOutputTitle").textContent=data.outputTitle;$("#caseDocumentType").textContent=data.type;$("#caseDocumentCode").textContent=data.code;$("#caseDocumentTitle").textContent=data.title;$("#caseDocumentText").textContent=data.text;$("#caseResultGrid").innerHTML=data.results.map(item=>`<div><span>${escapeHtml(item[0])}</span><p><strong>${escapeHtml(item[1])}</strong><small>${escapeHtml(item[2])}</small></p></div>`).join("");$$(".case-tab").forEach(btn=>btn.classList.toggle("active",btn.dataset.case===key))}
function setupCases(){$$(".case-tab").forEach(btn=>btn.addEventListener("click",()=>renderCase(btn.dataset.case)));$("#caseStartButton").addEventListener("click",()=>{const data=caseData[currentCaseKey];startProjectWithService(data.service,data.details)});renderCase("expose")}

function setWizardService(service){const radio=$$('[name="wizardService"]').find(input=>input.value===service);if(radio)radio.checked=true}
function startProjectWithService(service,notes){resetWizard(false);setWizardService(service);if(notes)$("#projectNotes").value=notes;saveDraft();showWizardStep(1);scrollToId("projekt");showToast("Leistung in neues Projekt übernommen")}
function showWizardStep(step){currentWizardStep=Math.min(4,Math.max(1,step));$$(".wizard-panel").forEach(panel=>panel.classList.toggle("active",Number(panel.dataset.panel)===currentWizardStep));$$(".wizard-step").forEach(btn=>btn.classList.toggle("active",Number(btn.dataset.step)===currentWizardStep));$("#wizardBackButton").classList.toggle("hidden",currentWizardStep===1);$("#wizardNextButton").classList.toggle("hidden",currentWizardStep===4);$("#createProjectButton").classList.toggle("hidden",currentWizardStep!==4);if(currentWizardStep===4)renderReview()}
function validateStep(step){if(step===2){const name=$("#projectName"),city=$("#city");if(!name.value.trim()){name.focus();showToast("Bitte einen Projektnamen eintragen");return false}if(!city.value.trim()){city.focus();showToast("Bitte einen Ort eintragen");return false}}return true}
function collectDraft(){return{service:$("[name='wizardService']:checked")?.value||"Eigentümerbericht",name:$("#projectName").value.trim(),objectType:$("#objectType").value,units:Math.max(1,Number($("#units").value)||1),street:$("#street").value.trim(),postalCode:$("#postalCode").value.trim(),city:$("#city").value.trim(),contactName:$("#contactName").value.trim(),contactEmail:$("#contactEmail").value.trim(),materials:$$('[name="material"]:checked').map(input=>input.value),photoCount:Math.max(0,Number($("#photoCount").value)||0),documentCount:Math.max(0,Number($("#documentCount").value)||0),fileNames:[...selectedFileNames],notes:$("#projectNotes").value.trim()}}
function saveDraft(){localStorage.setItem(DRAFT_KEY,JSON.stringify(collectDraft()))}
function applyDraft(draft){if(!draft)return;setWizardService(draft.service);$("#projectName").value=draft.name||"";$("#objectType").value=draft.objectType||"Wohnung";$("#units").value=draft.units||1;$("#street").value=draft.street||"";$("#postalCode").value=draft.postalCode||"";$("#city").value=draft.city||"";$("#contactName").value=draft.contactName||"";$("#contactEmail").value=draft.contactEmail||"";$$('[name="material"]').forEach(input=>input.checked=(draft.materials||[]).includes(input.value));$("#photoCount").value=draft.photoCount||0;$("#documentCount").value=draft.documentCount||0;selectedFileNames=draft.fileNames||[];renderSelectedFiles();$("#projectNotes").value=draft.notes||""}
function restoreDraft(){try{applyDraft(JSON.parse(localStorage.getItem(DRAFT_KEY)))}catch{localStorage.removeItem(DRAFT_KEY)}}
function renderSelectedFiles(){$("#selectedFiles").textContent=selectedFileNames.length?selectedFileNames.join(" · "):"Keine Dateien ausgewählt"}
function renderReview(){const d=collectDraft();const address=[d.street,[d.postalCode,d.city].filter(Boolean).join(" ")].filter(Boolean).join(", ")||"Noch keine vollständige Adresse";$("#projectReview").innerHTML=`<div class="review-group"><h4>Projekt</h4><dl><div><dt>Name</dt><dd>${escapeHtml(d.name||"–")}</dd></div><div><dt>Leistung</dt><dd>${escapeHtml(d.service)}</dd></div><div><dt>Objekt</dt><dd>${escapeHtml(d.objectType)}</dd></div><div><dt>Adresse</dt><dd>${escapeHtml(address)}</dd></div></dl></div><div class="review-group"><h4>Material</h4><dl><div><dt>Auswahl</dt><dd>${escapeHtml(d.materials.join(", ")||"Keine Auswahl")}</dd></div><div><dt>Fotos</dt><dd>${d.photoCount}</dd></div><div><dt>Dokumente</dt><dd>${d.documentCount}</dd></div><div><dt>Dateien</dt><dd>${d.fileNames.length}</dd></div></dl></div><div class="review-group"><h4>Ansprechpartner</h4><dl><div><dt>Name</dt><dd>${escapeHtml(d.contactName||"–")}</dd></div><div><dt>E-Mail</dt><dd>${escapeHtml(d.contactEmail||"–")}</dd></div><div><dt>Einheiten</dt><dd>${d.units}</dd></div></dl></div><div class="review-group"><h4>Hinweise</h4><p>${escapeHtml(d.notes||"Keine zusätzlichen Hinweise eingetragen.")}</p></div>`}
function generateProjectId(projects){const year=new Date().getFullYear();const numbers=projects.map(p=>Number(String(p.id).split("-").pop())).filter(Number.isFinite);const next=(numbers.length?Math.max(...numbers):0)+1;return `IN-${year}-${String(next).padStart(3,"0")}`}
function createOrUpdateProject(event){event.preventDefault();if(!validateStep(2))return;const draft=collectDraft();let projects=getProjects();if(editingProjectId){projects=projects.map(project=>project.id===editingProjectId?{...project,...draft,updatedAt:new Date().toISOString()}:project);selectedProjectId=editingProjectId;showToast("Projekt aktualisiert")}else{const project={...draft,id:generateProjectId(projects),statusIndex:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};projects.unshift(project);selectedProjectId=project.id;showToast("Projekt im Portal angelegt")}saveProjects(projects);localStorage.removeItem(DRAFT_KEY);resetWizard(false);renderPortal();scrollToId("portal")}
function resetWizard(clearDraft=true){editingProjectId=null;$("#projectWizard").reset();$("#objectType").value="Wohnung";$("#units").value=1;$("#photoCount").value=0;$("#documentCount").value=0;selectedFileNames=[];renderSelectedFiles();setWizardService("Eigentümerbericht");showWizardStep(1);if(clearDraft)localStorage.removeItem(DRAFT_KEY)}
function setupWizard(){restoreDraft();renderSelectedFiles();$("#wizardNextButton").addEventListener("click",()=>{if(!validateStep(currentWizardStep))return;saveDraft();showWizardStep(currentWizardStep+1)});$("#wizardBackButton").addEventListener("click",()=>showWizardStep(currentWizardStep-1));$$(".wizard-step").forEach(btn=>btn.addEventListener("click",()=>{const target=Number(btn.dataset.step);if(target<=currentWizardStep||validateStep(currentWizardStep))showWizardStep(target)}));$("#fileInput").addEventListener("change",event=>{selectedFileNames=Array.from(event.target.files).map(file=>file.name);renderSelectedFiles();saveDraft()});$("#projectWizard").addEventListener("input",saveDraft);$("#projectWizard").addEventListener("change",saveDraft);$("#projectWizard").addEventListener("submit",createOrUpdateProject)}

function projectAddress(project){return [project.street,[project.postalCode,project.city].filter(Boolean).join(" ")].filter(Boolean).join(", ")||project.city||"Adresse offen"}
function renderPortal(){const projects=getProjects();$("#projectCount").textContent=`${projects.length} ${projects.length===1?"Projekt":"Projekte"}`;const list=$("#projectList");if(!projects.length){list.innerHTML='<div class="project-list-empty">Noch keine Projekte angelegt.</div>';selectedProjectId=null}else{if(!selectedProjectId||!projects.some(p=>p.id===selectedProjectId))selectedProjectId=projects[0].id;list.innerHTML=projects.map(project=>`<button class="project-list-item ${project.id===selectedProjectId?"active":""}" type="button" data-project-id="${escapeHtml(project.id)}"><div class="project-list-item-top"><div><strong>${escapeHtml(project.name)}</strong><small>${escapeHtml(project.service)}</small></div><span class="mini-status">${escapeHtml(statusSteps[project.statusIndex].label)}</span></div><div class="project-list-item-meta"><span>${escapeHtml(project.id)}</span><span>${escapeHtml(project.city||"Ort offen")}</span></div></button>`).join("");$$('.project-list-item').forEach(btn=>btn.addEventListener("click",()=>{selectedProjectId=btn.dataset.projectId;renderPortal()}))}renderProjectDetail(projects.find(p=>p.id===selectedProjectId))}
function renderProjectDetail(project){const empty=$("#portalEmptyState"),detail=$("#projectDetail");if(!project){empty.classList.remove("hidden");detail.classList.add("hidden");return}empty.classList.add("hidden");detail.classList.remove("hidden");const progress=Math.round(((project.statusIndex+1)/statusSteps.length)*100);$("#detailProjectId").textContent=project.id;$("#detailProjectName").textContent=project.name;$("#detailProjectSubtitle").textContent=`${project.service} · ${project.objectType}`;$("#detailStatusBadge").textContent=statusSteps[project.statusIndex].label;$("#detailProgressText").textContent=`${progress}%`;$("#detailProgressBar").style.width=`${progress}%`;$("#detailObjectType").textContent=project.objectType;$("#detailAddress").textContent=projectAddress(project);$("#detailUnits").textContent=String(project.units||1);$("#detailContact").textContent=project.contactName||project.contactEmail||"Nicht eingetragen";const material=[...(project.materials||[])];if(project.photoCount)material.push(`${project.photoCount} Fotos`);if(project.documentCount)material.push(`${project.documentCount} Dokumente`);if((project.fileNames||[]).length)material.push(`${project.fileNames.length} Dateinamen`);$("#detailMaterialTags").innerHTML=(material.length?material:["Noch kein Material erfasst"]).map(item=>`<span>${escapeHtml(item)}</span>`).join("");$("#detailNotes").textContent=project.notes||"Keine zusätzlichen Hinweise eingetragen.";$("#detailTimeline").innerHTML=statusSteps.map((step,index)=>`<div class="timeline-step ${index<project.statusIndex?"done":index===project.statusIndex?"active":""}"><i>${index<project.statusIndex?"✓":index+1}</i><p><strong>${escapeHtml(step.label)}</strong><small>${escapeHtml(step.note)}</small></p></div>`).join("");$("#advanceStatusButton").disabled=project.statusIndex>=statusSteps.length-1;$("#advanceStatusButton").textContent=project.statusIndex>=statusSteps.length-1?"Projekt abgeschlossen":"Nächsten Status simulieren"}
function setupPortal(){const openNew=()=>{resetWizard();scrollToId("projekt")};$("#portalNewProjectButton").addEventListener("click",openNew);$("#emptyNewProjectButton").addEventListener("click",openNew);$("#advanceStatusButton").addEventListener("click",()=>{const projects=getProjects();const index=projects.findIndex(p=>p.id===selectedProjectId);if(index<0)return;if(projects[index].statusIndex<statusSteps.length-1){projects[index].statusIndex+=1;projects[index].updatedAt=new Date().toISOString();saveProjects(projects);renderPortal();showToast("Projektstatus aktualisiert")}});$("#editProjectButton").addEventListener("click",()=>{const project=getProjects().find(p=>p.id===selectedProjectId);if(!project)return;editingProjectId=project.id;applyDraft(project);showWizardStep(1);scrollToId("projekt");showToast("Projekt zur Bearbeitung geöffnet")});$("#deleteProjectButton").addEventListener("click",()=>{const project=getProjects().find(p=>p.id===selectedProjectId);if(!project)return;if(!confirm(`Projekt ${project.id} wirklich löschen?`))return;saveProjects(getProjects().filter(p=>p.id!==selectedProjectId));selectedProjectId=null;renderPortal();showToast("Projekt gelöscht")});renderPortal()}

function setupMap(){if(typeof L==="undefined"||!$("#map"))return;mapInstance=L.map("map",{scrollWheelZoom:false}).setView([51.4516,6.6408],9);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(mapInstance);L.circle([51.4516,6.6408],{radius:50000,color:"#2563eb",weight:2,fillColor:"#2563eb",fillOpacity:.1}).addTo(mapInstance);[[51.4516,6.6408,"Moers"],[51.4963,6.5459,"Kamp-Lintfort"],[51.4344,6.7623,"Duisburg"],[51.3388,6.5853,"Krefeld"]].forEach(([lat,lng,name])=>L.marker([lat,lng]).addTo(mapInstance).bindPopup(name));setTimeout(()=>mapInstance.invalidateSize(),250)}

function init(){setupNavigation();setupServices();setupCases();setupWizard();setupPortal();setupMap()}
document.addEventListener("DOMContentLoaded",init);
